CREATE TABLE IF NOT EXISTS warehouse_receipt (
    id uuid NOT NULL,
    actual_weight_kg numeric(10,3),
    actual_weight_lbs numeric(10,2),
    agent_name varchar(150),
    awb_reported_pieces integer,
    booked_in_acoms boolean,
    broker_id_doc_url varchar(255),
    broker_id_num varchar(50),
    broker_name varchar(150),
    broker_sig_url varchar(255),
    cash_only boolean,
    chargeable_weight_kg numeric(10,3),
    chargeable_weight_lbs numeric(10,2),
    consignee_name varchar(150),
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_name varchar(150),
    customs_completed boolean,
    delivered_by_id_doc_url varchar(255),
    delivered_by_id_num varchar(50),
    delivered_by_name varchar(150),
    delivered_by_sig_url varchar(255),
    destination varchar(3),
    dim_factor_dom integer,
    dim_factor_intl integer,
    dock_signature text,
    docs_provided boolean,
    gateway_cfs varchar(10),
    loose_tender boolean,
    mawb_weight_greatest numeric(10,3),
    observations varchar(255),
    origin varchar(3),
    piece_count integer,
    pre_built boolean,
    print_name varchar(150),
    receipt_date timestamptz,
    receipt_doc_url varchar(255),
    received_by_id_doc_url varchar(255),
    received_by_id_num varchar(50),
    received_by_name varchar(150),
    received_by_sig_url varchar(255),
    remarks text,
    shipper_comment varchar(255),
    shipper_name varchar(150),
    shipper_reported_weight numeric(10,3),
    start_datetime timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    airline_id uuid NOT NULL,
    created_by_user_id uuid,
    mawb_id uuid NOT NULL,
    mawb_number varchar(50),
    supporting_docs text DEFAULT '[]',
    hawb_id uuid,
    excel_data bytea,
    pdf_data bytea,
    correction_of_id uuid,
    correction_number integer DEFAULT 1,
    superseded boolean DEFAULT false,
    correction_reason varchar(500),
    corrected_by_name varchar(150),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS receipt_piece (
    id uuid NOT NULL,
    chargeable_kg numeric(10,3),
    chargeable_lbs numeric(10,2),
    dim_weight_kg numeric(10,3),
    dim_weight_lbs numeric(10,2),
    hawb_id uuid,
    height_in numeric(10,2),
    length_in numeric(10,2),
    piece_number integer,
    pieces integer NOT NULL DEFAULT 1,
    receipt_id uuid NOT NULL,
    scale_weight_kg numeric(10,3),
    scale_weight_lbs numeric(10,2),
    width_in numeric(10,2),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_receipt_piece_receipt_id ON receipt_piece(receipt_id);
CREATE INDEX IF NOT EXISTS idx_warehouse_receipt_mawb_id ON warehouse_receipt(mawb_id);
CREATE INDEX IF NOT EXISTS idx_warehouse_receipt_airline_id ON warehouse_receipt(airline_id);
CREATE INDEX IF NOT EXISTS idx_warehouse_receipt_superseded ON warehouse_receipt(superseded);
